// Italian copy remains in the components. These entries only supply the English view.
export const projectEnglishCopy: Record<string, string> = {
  'Cos\'è': 'What is',
  'Bussola Verde?': 'Bussola Verde?',
  'Un ecosistema digitale che trasforma il parco in un percorso su misura, rendendo il visitatore esploratore attivo.': 'A digital ecosystem that turns the garden into a tailored journey, making each visitor an active explorer.',
  'Interattività': 'Interactivity',
  'PANNELLI DIGITALI E QR ACCRESCONO LA CONOSCENZA.': 'DIGITAL DISPLAYS AND QR CODES EXPAND KNOWLEDGE.',
  'Pannelli digitali e QR accrescono la conoscenza.': 'Digital displays and QR codes expand knowledge.',
  'Percorsi Agili': 'Flexible Routes',
  "ITINERARI SCELTI TRAMITE I TOTEM ALL'INGRESSO.": 'ROUTES CHOSEN AT THE ENTRANCE KIOSKS.',
  "Itinerari scelti tramite i Totem all'ingresso.": 'Routes chosen at the entrance kiosks.',
  'Accessibilità': 'Accessibility',
  'APP USER-FRIENDLY E MAPPE INCLUSIVE PER TUTTI.': 'AN EASY-TO-USE APP AND INCLUSIVE MAPS FOR EVERYONE.',
  'App user-friendly e mappe inclusive per tutti.': 'An easy-to-use app and inclusive maps for everyone.',
  'Metodologia': 'Research',
  'di Ricerca': 'Methodology',
  'Metodologia di Ricerca': 'Research Methodology',
  'SONDAGGI': 'SURVEYS',
  'INTERVISTE': 'INTERVIEWS',
  'Sondaggi': 'Surveys',
  'Interviste': 'Interviews',
  'Orientamento': 'Wayfinding',
  'NESSUNA GUIDA PER NON ESPERTI.': 'NO GUIDANCE FOR NON-EXPERTS.',
  'Nessuna guida per non esperti.': 'No guidance for non-experts.',
  'Coinvolgimento': 'Engagement',
  'ESPERIENZA PASSIVA E VELOCE (5 MIN).': 'A PASSIVE, BRIEF EXPERIENCE (5 MIN).',
  'Esperienza passiva e veloce (5 min).': 'A passive, brief experience (5 min).',
  'Informazioni': 'Information',
  'MANCANO SPIEGAZIONI OLTRE AL NOME SCIENTIFICO.': 'NO EXPLANATIONS BEYOND THE SCIENTIFIC NAME.',
  'Mancano spiegazioni oltre al nome scientifico.': 'There are no explanations beyond the scientific name.',
  'Come ti orienti?': 'How do you find your way?',
  'Segnaletica': 'Signs',
  'Casuale': 'At random',
  'Useresti QR code interattivi?': 'Would you use interactive QR codes?',
  'Forse': 'Maybe',
  'Sì': 'Yes',
  'Utilità di un Totem Digitale?': 'Would a Digital Kiosk Help?',
  'Mancanze Informative?': 'Missing Information?',
  '"Migliorerebbe l\'esperienza, permettendo di orientarsi e prepararsi prima della visita."': '"It would improve the experience, helping us find our way and prepare before the visit."',
  '"Sì, mancano dettagli scientifici chiari oltre al nome della pianta."': '"Yes, clear scientific details beyond the plant name are missing."',
  'Problemi riscontrati': 'Problems Identified',
  'Disorientamento dei visitatori': 'Visitors losing their way',
  'Informazione analogica statica': 'Static printed information',
  'Mancanza di interazione': 'Lack of interaction',
  'Poche informazioni utili': 'Limited useful information',
  'Soluzioni adottate': 'Solutions Implemented',
  "Totem interattivi all'ingresso": 'Interactive kiosks at the entrance',
  'QR Code per approfondimenti': 'QR codes for more information',
  'Web-App dedicata': 'Dedicated web app',
  'Mappa digitale a portata di mano': 'A digital map at your fingertips',
  "Totem all'ingresso": 'Kiosks at the Entrance',
  'Selezione immediata di percorsi tematici e mappa generale.': 'Instant selection of themed routes and an overview map.',
  'Approfondimenti istantanei direttamente sul proprio smartphone.': 'Instant access to more information on your smartphone.',
  'Web-App Dedicata': 'Dedicated Web App',
  'Esperienza guidata, accessibile e interattiva in tasca.': 'A guided, accessible and interactive experience in your pocket.',
  'Informazioni alla portata di tutti': 'Information for Everyone',
  'Inserimento di una mappa generale a portata di mano e curiosità sulle piante.': 'An overview map at your fingertips, with interesting facts about the plants.',
  'Disorientamento': 'Disorientation',
  'I visitatori si perdono facilmente senza mappe interattive.': 'Visitors easily get lost without interactive maps.',
  'Informazione Statica': 'Static Information',
  'La cartellonistica analogica fornisce solo nomi scientifici.': 'Printed signs only provide scientific names.',
  'Scarsa Interazione': 'Limited Interaction',
  'Visita frettolosa senza un effettivo coinvolgimento digitale.': 'A rushed visit without meaningful digital engagement.',
  'Mancanza di informazioni': 'Lack of Information',
  'Non è presente una mappa, poche informazioni utili e interessanti sulle piante.': 'There is no map and little useful or engaging information about the plants.',
  "L'utente Ideale": 'The Ideal Visitor',
  '"Voglio connettermi alla natura e approfondire la mia conoscenza scientifica senza barriere, in modo dinamico e intuitivo."': '"I want to connect with nature and deepen my scientific knowledge without barriers, in a dynamic and intuitive way."',
  'Nuova residente a Catania (Studentessa).': 'New resident of Catania (student).',
  'NECESSITÀ': 'NEEDS',
  'Necessità': 'Needs',
  'Informazioni repentine tramite smartphone.': 'Quick access to information on a smartphone.',
  'OBIETTIVO': 'GOAL',
  'Obiettivo': 'Goal',
  'Esplorazione scientifica intuitiva.': 'Intuitive scientific exploration.',
  'ORIGINE': 'ORIGIN',
  'Origine': 'Origin',
  'Colombia, ricca di biodiversità.': 'Colombia, rich in biodiversity.',
  'Orto Generale': 'General Garden',
  'Orto Siculo': 'Sicilian Garden',
  'Arido': 'Arid',
  'Fontanella': 'Fountain',
  'Bagni': 'Restrooms',
  'Esplora la ricca biodiversità della nostra collezione di piante tropicali, progettata per stupire e ispirare.': 'Explore the rich biodiversity of our tropical plant collection, designed to amaze and inspire.',
  'Scegli il percorso': 'Choose a route',
  'VERSIONE MOBILE': 'MOBILE VERSION',
  'VERSIONE TOTEM': 'KIOSK VERSION',
  'Versione Mobile': 'Mobile Version',
  'Versione Totem': 'Kiosk Version',
  'PROVALO': 'TRY IT',
  'Provalo': 'Try It',
  "Puoi provare il prototipo dall'anteprima a sinistra o cliccando sul pulsante qui sotto": 'Try the prototype in the preview on the left or click the button below',
  'Prova il Prototipo': 'Try the Prototype',
  'Esplora altri progetti': 'Explore Other Projects',
  'Altri progetti': 'Other projects',
  'TORNA ALLA HOME': 'BACK TO HOME',
  'Introduzione Urban StreetArt Sicily': 'Introduction to Urban StreetArt Sicily',
  'Obiettivo Urban StreetArt Sicily': 'Urban StreetArt Sicily Goal',
  'Adattabilità Urban StreetArt Sicily': 'Urban StreetArt Sicily Adaptability',
  'Applicazione responsive Urban StreetArt Sicily': 'Urban StreetArt Sicily Responsive App',
  'Introduzione al progetto Italo Treni': 'Introduction to the Italo Treni Project',
  'Wireframe dell’app Italo': 'Italo App Wireframes',
  'Paginazione wireframe': 'Wireframe Pages',
  'Wireframe precedente': 'Previous Wireframe',
  'Wireframe successivo': 'Next Wireframe',
  'Versione negativa del logo Urban StreetArt Sicily': 'Negative version of the Urban StreetArt Sicily logo',
  'Urban StreetArt Sicily logo negativo': 'Urban StreetArt Sicily negative logo',
  'Mappa d’Italia: usa il nome della regione per cambiare selezione': 'Map of Italy: use the region name to change the selection',
  'INTRODUZIONE': 'INTRODUCTION',
  'Prototipo': 'Prototype',
  'Prima': 'Before',
  'Dopo': 'After',
  "Rebranding dell'identità visiva": 'Rebranding the visual identity',
  'di Urban StreetArt Sicily': 'of Urban StreetArt Sicily',
  "Pagina Instagram dedicata alla diffusione dell'arte urbana in Sicilia, con l'obiettivo di trasformarla in un vero e proprio portale digitale.": 'An Instagram page devoted to urban art in Sicily, with the goal of turning it into a true digital platform.',
  'Creare un’identità visiva forte, contemporanea e coerente, capace di rappresentare l’energia dell’arte urbana e rendere il progetto riconoscibile su tutti i canali digitali.': 'Create a strong, contemporary and consistent visual identity that captures the energy of urban art and makes the project recognizable across every digital channel.',
  "Un'estetica moderna, urbana e ad alto contrasto. L'identità visiva è progettata per far risaltare le opere d'arte di strada, utilizzando una base scura punteggiata da accenti geometrici e di colore decisi.": 'A modern, urban aesthetic with strong contrast. The visual identity makes street art stand out through a dark foundation punctuated by bold geometric and color accents.',
  'Eventi': 'Events',
  'Artisti': 'Artists',
  'ADATTABILITÀ': 'ADAPTABILITY',
  "Il redesign dell'applicazione di Italo Treno si concentra sull'abbattimento del carico cognitivo durante la ricerca, selezione e pagamento delle tratte ad alta velocità.": 'The redesign of the Italo train app focuses on reducing cognitive load when searching for, selecting and paying for high-speed journeys.',
  'CRITICITÀ': 'CRITICAL ISSUES',
  'Criticità': 'Critical Issues',
  'Navigazione': 'Labyrinthine',
  'Labirintica': 'Navigation',
  'Gerarchia': 'Missing',
  'Visiva Assente': 'Visual Hierarchy',
  'Frizioni': 'Color',
  'Cromatiche': 'Friction',
  'Discontinuità': 'Inconsistent',
  "d'Interfaccia": 'Interface',
  "Eccessiva ridondanza dei menu con voci duplicate e sezioni superflue che rallentano il flusso d'acquisto disorientando l'utente.": 'Redundant menus, duplicate entries and unnecessary sections slow down purchasing and confuse users.',
  'Testi monocromatici e dimensionamento errato (prezzi minuscoli, titoli non centrati) rendono faticosa la scansione rapida.': 'Monochrome text and poor sizing (tiny prices, misaligned headings) make quick scanning difficult.',
  'Uso fuorviante dei colori: il rosso viene usato per evidenziare messaggi positivi. Scarso contrasto sulle call to action primarie.': 'Misleading use of color: red highlights positive messages, while primary calls to action lack contrast.',
  "Spaziature incoerenti, layout frammentato e icone fuori standard che minano pesantemente la percezione qualitativa dell'app.": 'Inconsistent spacing, fragmented layouts and nonstandard icons undermine the perceived quality of the app.',
  'SVILUPPO WIREFRAME': 'WIREFRAME DEVELOPMENT',
  'Sviluppo Wireframe': 'Wireframe Development',
  'Sono stati analizzati i flussi principali degli utenti e le funzionalità più utilizzate.': 'The main user flows and most frequently used features were analyzed.',
  'Successivamente è stato sviluppato un wireframe a bassa fedeltà per definire la struttura della schermata, la disposizione dei contenuti e la gerarchia delle informazioni.': 'A low-fidelity wireframe was then created to define the screen structure, content layout and information hierarchy.',
  'PRIMA E DOPO': 'BEFORE AND AFTER',
  'CERCA BIGLIETTO': 'FIND A TICKET',
  'I TUOI BIGLIETTI': 'YOUR TICKETS',
  'OFFERTE': 'OFFERS',
};
